name: wallet
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked_card_carousel: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  intl_phone_number_input: ^0.7.0+2
  provider: ^6.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/login/
    - assets/home/
    - assets/transaction/
    - assets/users/
    - assets/
